services:
  bitbag_sylius_catalog_plugin.form.type.catalog:
    class: BitBag\SyliusCatalogPlugin\Form\Type\CatalogType
    arguments:
      - "%bitbag_sylius_catalog_plugin.model.catalog.class%"
      - [ 'bitbag' ]
    tags:
      - { name: form.type }
  bibag_sylius_catalog_plugin/form.type.translation.catalog:
    class: BitBag\SyliusCatalogPlugin\Form\Type\Translation\CatalogTranslationType
    arguments:
      - "%bitbag_sylius_catalog_plugin.model.catalog_translation.class%"
      - [ 'bitbag']
    tags:
      - { name: form.type }
