sylius_grid:
  grids:
    bitbag_sylius_catalog_plugin_admin_catalog:
      driver:
        name: doctrine/orm
        options:
          class: BitBag\SyliusCatalogPlugin\Entity\Catalog
      fields:
        name:
          type: string
          label: sylius.ui.name
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete


