sylius_grid:
  grids:
    app_admin_catalog:
      driver:
        name: doctrine/orm
        options:
          class: Acme\SyliusExamplePlugin\Entity\Catalog
      fields:
        name:
          type: string
          label: sylius.ui.name


