imports:
  - { resource: "@BitBagSyliusCatalogPlugin/Resources/config/resources.yaml" }
  - { resource: "@BitBagSyliusCatalogPlugin/Resources/config/services.xml" }
  - { resource: "@BitBagSyliusCatalogPlugin/Resources/config/grids.yaml" }
  - { resource: "@BitBagSyliusCatalogPlugin/Resources/config/_sylius.yaml" }
