services:
  acme_sylius_example_plugin.listener.admin.menu_builder:
    class: Acme\SyliusExamplePlugin\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }
