# Delete these routes and define your own shop routes here

bitbag_sylius_catalog_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: BitBagSyliusCatalogPlugin:Greeting:staticallyGreet
        name: ~

bitbag_sylius_catalog_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: BitBagSyliusCatalogPlugin:Greeting:dynamicallyGreet
        name: ~
