sylius_resource:
  resources:
    bitbag_sylius_catalog_plugin.catalog:
      driver: doctrine/orm
      classes:
        model: BitBag\SyliusCatalogPlugin\Entity\Catalog
        interface: BitBag\SyliusCatalogPlugin\Entity\CatalogInterface
        form: BitBag\SyliusCatalogPlugin\Form\Type\CatalogType
