sylius_resource:
  resources:
    acme_sylius_example_plugin.catalog:
      driver: doctrine/orm
      classes:
        model: BitBag\SyliusCatalogPlugin\Entity\Catalog
        interface: BitBag\SyliusCatalogPlugin\Entity\CatalogInterface
