sylius_grid:
  grids:
    bitbag_sylius_catalog_plugin_admin_catalog:
      driver:
        name: doctrine/orm
        options:
          class: "%bitbag_sylius_catalog_plugin.model.catalog.class%"
      fields:
        name:
          type: string
          label: sylius.ui.name
        code:
          type: string
          label: sylius.ui.code
        startDate:
          type: datetime
          label: sylius.ui.starts_at
        endDate:
          type: datetime
          label: sylius.ui.ends_at
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
      filters:
        code:
          type: string
          label: sylius.ui.code
          options:
            fields: [ code ]
        name:
          type: string
          label: sylius.ui.name
          options:
            fields: [translations.name]
