bitbag_sylius_catalog_plugin_admin_catalog:
  resource: |
    alias: bitbag_sylius_catalog_plugin.catalog
    except: ['show']
    redirect: update
    templates: SyliusAdminBundle:Crud
    section: admin
    grid: bitbag_sylius_catalog_plugin_admin_catalog
  type: sylius.resource
