bitbag_sylius_catalog_plugin_admin_catalog:
  resource: |
    alias: bitbag_sylius_catalog_plugin.catalog
    except: ['show']
    redirect: update
    templates: SyliusAdminBundle:Crud
    section: admin
    grid: bitbag_sylius_catalog_plugin_admin_catalog
    vars:
      all:
          templates:
              form: "@BitBagSyliusCatalogPlugin/Catalog/Catalog/_form.html.twig"
      index:
          icon: block layout
      route:
          parameters:
              code: $type
  type: sylius.resource
